import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { isGCSStaff } from "@/lib/auth-utils";
import { sendMail } from "@/lib/email";

function pitchToHtml(businessName: string, pitchText: string): string {
  // Split by ## headings and format each section
  const sections = pitchText.split(/\n##\s+/).filter(Boolean);

  const sectionHtml = sections
    .map((section) => {
      const lines = section.split("\n");
      const heading = lines[0].trim();
      const body = lines
        .slice(1)
        .join("\n")
        .trim()
        // Bold **text**
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        // Bullet and numbered list items → HTML list items
        .replace(/^[-•*]\s+(.+)/gm, "<li>$1</li>")
        .replace(/^\d+\.\s+(.+)/gm, "<li>$1</li>")
        // Paragraphs for non-list lines (split on double newlines)
        .split(/\n\n+/)
        .map((p) => p.trim())
        .filter(Boolean)
        .map((p) => {
          if (p.includes("<li>")) {
            return `<ul style="margin:8px 0 8px 20px; padding:0; color:#455A64;">${p}</ul>`;
          }
          return `<p style="margin:8px 0; color:#455A64; line-height:1.6;">${p.replace(/\n/g, "<br/>")}</p>`;
        })
        .join("\n");

      return `
        <div style="margin-bottom:24px; border-left:4px solid #1565C0; padding-left:16px;">
          <h3 style="margin:0 0 10px 0; font-size:15px; color:#0A1929; font-weight:700;">${heading}</h3>
          ${body}
        </div>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>GCS Sales Pitch — ${businessName}</title>
</head>
<body style="margin:0; padding:0; background:#F5F7FA; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:680px; margin:40px auto; background:#FFFFFF; border-radius:12px; overflow:hidden; box-shadow:0 4px 6px rgba(0,0,0,0.07);">

    <!-- Header -->
    <div style="background:#1565C0; padding:32px 40px;">
      <img src="https://www.itatgcs.com/logo.png" alt="GCS" style="height:40px; filter:brightness(0) invert(1);" />
      <h1 style="margin:16px 0 4px 0; color:white; font-size:22px; font-weight:800;">
        Sales Intelligence Report
      </h1>
      <p style="margin:0; color:rgba(255,255,255,0.8); font-size:14px;">
        Prepared by GCS AI Pitch Board for <strong>${businessName}</strong>
      </p>
    </div>

    <!-- Intro -->
    <div style="background:#EEF2FF; padding:16px 40px; border-bottom:1px solid #E0E7FF;">
      <p style="margin:0; font-size:13px; color:#3730A3;">
        ✨ This pitch was generated by GCS's AI Sales Intelligence system, tailored specifically to <strong>${businessName}</strong> based on live website analysis and security assessment.
      </p>
    </div>

    <!-- Pitch Sections -->
    <div style="padding:32px 40px;">
      ${sectionHtml}
    </div>

    <!-- Footer -->
    <div style="background:#F5F7FA; padding:24px 40px; text-align:center; border-top:1px solid #E8EDF2;">
      <p style="margin:0 0 4px 0; font-weight:600; color:#374151;">Global Computing Solutions</p>
      <p style="margin:0; font-size:12px; color:#9CA3AF;">
        <a href="https://www.itatgcs.com" style="color:#1565C0; text-decoration:none;">www.itatgcs.com</a>
        &nbsp;|&nbsp;
        <a href="mailto:info@itatgcs.com" style="color:#1565C0; text-decoration:none;">info@itatgcs.com</a>
      </p>
      <p style="margin:8px 0 0 0; font-size:11px; color:#9CA3AF;">This is an internal sales document prepared by GCS for prospecting purposes.</p>
    </div>
  </div>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user || !isGCSStaff(session.user.role ?? "")) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    const { recipientEmail, businessName, pitchText } = await req.json();
    if (!recipientEmail || !businessName || !pitchText) {
      return NextResponse.json({ error: "recipientEmail, businessName, and pitchText are required" }, { status: 400 });
    }

    await sendMail({
      to: recipientEmail,
      subject: `GCS Sales Intelligence — ${businessName}`,
      html: pitchToHtml(businessName, pitchText),
      replyTo: "billing@itatgcs.com",
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    return NextResponse.json({ error: err instanceof Error ? err.message : "Failed to send email" }, { status: 500 });
  }
}
